### ISSUE TITLE
CloudFormation: when no tags are present, Yor renders an incorrect template

### ISSUE THREAD

**Issue by kristofwillen** [bridgecrewio/yor#109]
Take this sample minimal S3 CloudFormation input template:

```

---
AWSTemplateFormatVersion: 2010-09-09
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
    DeletionPolicy: Retain
```

when running `yor tag -d .`, yor adds the required tags, but doesn't add a 'Tags:' directive:

```
---
AWSTemplateFormatVersion: 2010-09-09
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
    DeletionPolicy: Retain
    - Key: git_repo
      Value: yor-sandbox
    - Key: git_file
      Value: s3.yml
[...]
```

thus rendering the CloudFormation template invalid. 
I would expect yor to issue an error saying it expects the 'Tags:' directive, or to add it itself.  
When tagging a similar minimal Terraform s3.tf file, yor behaves correctly.
