### ISSUE TITLE
CloudFormation: yor copies resources instead of modifying them

### ISSUE THREAD

**Issue by kristofwillen** [bridgecrewio/yor#114]
Take this sample CloudFormation template which defines a VPC with some additional resources:


```
---
AWSTemplateFormatVersion: 2010-09-09
Description:  This template deploys a VPC, with a pair of public and private subnets spread
  across two Availability Zones. It deploys an internet gateway, with a default
  route on the public subnets. It deploys a pair of NAT gateways (one in each AZ),
   and default routes for them in the private subnets.

Parameters:
  EnvironmentName:
    Description: An environment name that is prefixed to resource names
    Type: String

  VpcCIDR:
    Description: Please enter the IP range (CIDR notation) for this VPC
    Type: String
    Default: 10.192.0.0/16

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCIDR
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Ref EnvironmentName

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Ref EnvironmentName
 ```

When running 'yor tag -d .', yor will add a resource block for each defined resource :
 ```
$ yor tag -d .
$ cat vpc.yml
[...]
Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCIDR
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
           Value: EnvironmentName
        - Key: git_file
          Value: vpc.yml
        - Key: git_commit
          Value: b9ea9bd11725f65d97ee897e8825214c7e182cc7
        - Key: git_modifiers
          Value: kristof.willen
        - Key: git_last_modified_at
          Value: "2021-06-01 12:31:19"
        - Key: yor_trace
          Value: 0d4a31e9-90ce-452e-b946-c731e3285024
[...]
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCIDR
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Ref EnvironmentName

```


So I have now 2 VPC resource blocks defined, which breaks my CF template: 
```
$ cfn-lint ./vpc.yml    
E0000 Duplicate resource found "VPC" (line 48)
./vpc.yml:48:3
```

Additional info:
```
$ yor --version                                                                                                                                                                                                                                                                                                                                     
yor version 0.1.38
```
