### ISSUE TITLE
Cloudformation: yor overwrites existing tag values

### ISSUE THREAD

**Issue by kristofwillen** [bridgecrewio/yor#117]
Take this sample VPC CloudFormation template: 
```
---
AWSTemplateFormatVersion: 2010-09-09

Parameters:
  EnvironmentName:
    Description: An environment name that is prefixed to resource names
    Type: String

  VpcCIDR:
    Description: Please enter the IP range (CIDR notation) for this VPC
    Type: String
    Default: 10.192.0.0/16

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCIDR
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Ref EnvironmentName
 
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Ref EnvironmentName
```

When running yor, it correctly adds tags, but it changes the Name tag (the !Ref is removed) :
```
$ yor tag -d .
[...]
$ cat vpc.yml
[...]
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCIDR
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: EnvironmentName
        - Key: yor_trace
          Value: def86a84-eff9-4054-a7cb-1890919a6bb5
[...]
```
