### ISSUE TITLE
Cloudformation: empty (null) tags cause stack "CREATE_FAILED"

### ISSUE THREAD

**Issue by rollwagen** [bridgecrewio/yor#122]
Context: using yor (version 0.1.47) to tag cloudformation yaml file in local git repo (git init)

Tags are successfully created (see yaml snipped below), however, the empty tags (e.g. git_org) cause that cloudformation create stack to fail with:
```
CREATE_FAILED
Value ( git_org ) for parameter value is invalid.
Tag value cannot be null.
Use empty string instead. (Service: AmazonEC2; Status Code: 400; Error Code: InvalidParameterValue; Request ID: 0ade36-f7ec-4716-b787-42fb7bf8b; Proxy: null)
```

```
Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref 'InstanceType'
      SecurityGroups: [!Ref 'InstanceSecurityGroup']
      KeyName: !Ref 'KeyName'
      ImageId: !Ref 'LatestAmiId'
      Tags:
        - Key: yor_trace
          Value: 83d7be13-2c13-4f2d-92a0-5d88e44437c6
        - Key: Environment
          Value: rollwagen-dev
        - Key: git_commit
          Value: 54f7425be387138d3381c760d8d067b499bb8459
        - Key: git_modifiers
          Value: rollwagen
        - Key: git_last_modified_at
          Value: "2021-06-06 11:10:44"
        - Key: git_last_modified_by
          Value: emailaddress@email.com
        - Key: git_org
        - Key: git_repo
        - Key: git_file
          Value: EC2InstanceWithSecurityGroupSample.yaml
```
