### ISSUE TITLE
Yor doesn't parse references in cloudformation

### ISSUE THREAD

**Issue by blackdenc** [bridgecrewio/yor#165]
**Describe the bug**
When running `yor tag -d .` with yor v0.1.84 in a directory with cloudformation templates, any that use a parameter for EBS size return the below warning, and don't get tagged.

```
ERROR: json: cannot unmarshal string into Go struct field Instance_Ebs.Properties.BlockDeviceMappings.Ebs.VolumeSize of type int
2021/07/07 15:16:15 [WARNING] There was an error processing the cloudformation template template.yml: json: cannot unmarshal string into Go struct field Template.Resources of type int

  __    __
  \ \  / /
   \ \/ /___  _  ____
    \  /  _ \| |/  __|
    | |  |_| |   /
    |_|\____/|__|v0.1.84
 Yor Findings Summary
 Scanned Resources:       0
 New Resources Traced:    0
 Updated Resources:       0
```

**To Reproduce**
1. Use the below cloudformation template:
```
Parameters:
  EbsSize:
    Description: Please provider the extra EBS size you need
    Type: Number
    Default: 20
Resources:
  Ec2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0d57f0639aae57eb6
      InstanceType: t3.small
      KeyName: <Use your own key>
      SecurityGroupIds: [<Security Group>]
      SubnetId: <Subnet ID>
      BlockDeviceMappings:
        - DeviceName: /dev/xvdf
          Ebs:
            DeleteOnTermination: true
            Encrypted: true
            VolumeSize: !Ref EbsSize
            VolumeType: gp2
```
2. Run cli command  `yor tag -d .`
3. See error
4. Comment out the line `VolumeSize: !Ref EbsSize`
5. Re-run cli command `yor tag -d .`
6. See the command is successful

**Expected behavior**
Yor should add tags to cloudformation that use parameters

**Desktop (please complete the following information):**
 - OS: MacOS Mojave 10.14.6
 - Yor Version: v0.1.84
