### ISSUE TITLE
GCP requirements for labels

### ISSUE THREAD

**Issue by brettcurtis** [bridgecrewio/yor#248]
Label requirements for GCP are [here](https://cloud.google.com/resource-manager/docs/creating-managing-labels#requirements)

Trying to use yor in Google Cloud fails:

```hcl
# Project Module
# https://github.com/my-org/terraform-google-project

module "project" {
  source = "git@github.com:my-org/terraform-google-project?ref=v2.1.3"

  cost_center       = "uZZZ"
  folder_id         = var.folder_id
  prefix            = "shared"
  system            = "services"
  env               = var.env
  random_project_id = var.random_project_id

  labels = {
    team                 = "ops"
    yor_trace            = "8019ee39-ca38-4a8d-8b7a-d50ffd353f5c"
    git_commit           = "c828864803f716011793b240628c4311330de7d8"
    git_file             = "global/main.tf"
    git_last_modified_at = "2021-11-03 13:13:21"
    git_last_modified_by = "my-name@my-org.com"
    git_modifiers        = "my-name"
    git_org              = "my-org"
    git_repo             = "my-gcp-repo"
  }
}
```

ERROR:
```none
Error: Error updating project "my-services-tf21ee98-sb": googleapi: Error 400: field [project.labels] has issue [Label value 'global/main.tf' violates format constraints. The value can only contain lowercase letters, numeric characters, underscores and dashes. The value can be at most 63 characters long. International characters are allowed.], badRequest
```

In this case it's grumpy about the directory "/" but email etc will fail too.

**Describe the solution you'd like**
Honestly, I'd like to see Google do better here but I'm afraid that will be a challenge :D Maybe we ca use "-" everywhere for example:

```hcl
    git_file             = "global-main.tf"
    git_last_modified_at = "2021-11-03-13-13-21"
    git_last_modified_by = "my-name-my-org-com"
    git_modifiers        = "my-name"
    git_org              = "my-org"
```

My current W/A is to skip those tags for now in pre-commit:

```yaml
  - repo: git://github.com/bridgecrewio/yor
    rev: 0.1.128
    hooks:
      - id: yor
        name: yor
        entry: yor tag --directory
        args: ["global", "regional", "--skip-tags git_last_modified_by,git_last_modified_at,git_file"]
        language: golang
        types: [terraform]
```
