### ISSUE TITLE
tag_group level directory filters are allowed but not supported 

### ISSUE THREAD

**Issue by BorisO** [bridgecrewio/yor#253]
**Describe the bug**
Based on the [docs](https://yor.io/3.Custom%20Taggers/Custom_tagger_YAML.html#running-yaml-based-custom-tagger), directory filters for tag groups are seemingly only supported for each tag in the tag group. For example:
```
tag_groups:
  - name: devops
    tags:
      - name: group
        value:
          default: devops
        filters:
          directory: apps/datadog
```

We would like to be able to use the directory filter on the tag_group level instead of per tag. For example:
```
tag_groups:
  - name: datadog
    tags: 
      - name: group
        value:
          default: devops
      - name: env
        value:
          default: prod
    filters:
      directory: apps/datadog
  - name: jenkins
    tags: 
      - name: group
        value:
          default: infra
      - name: env
        value:
          default: dev
    filters:
      directory: apps/jenkins
```
While yor is able to run with this config the directory filters are not respected at all. 
When run with the above config file there there are resources in the same file which have tags from each of the different groups.
For example:
```
resource "aws_instance" "test" {
  ....
  ....

  tags = {
    group                = "devops"
    env                   = "prod"
  }
}

resource "aws_eip" "test" {
  ....
  ....
  tags = {
    group                = "infra"
    env                   = "dev"
  }
}
```
Even files that do not correspond to the directory filters are tagged as well (files in the other subdirectories of `apps/`). 

**Expected behavior**
It isn't clear if this is something that is currently supported. If not, yor shouldn't be able to run with an incorrect config file.

**Desktop (please complete the following information):**
 - OS: `macOS Catalina 10.15.2`
 - Yor Version `0.1.128`
