### ISSUE TITLE
Custom tagger replacing key and value if they are the same

### ISSUE THREAD

**Issue by jdorsman-bhvr** [bridgecrewio/yor#277]
**Describe the bug**
Upon using a custom tagger defined with the YAML format, I noticed that if you use placeholders as defaults that are the same value as the key name, changing the value also overrides the key name. It appears that the find/replace logic is too loose.

**To Reproduce**
1. Create a custom tagger in YAML format like this:

```yaml
tag_groups:
  - name: tagger-test
    tags:
      - name: project
        value:
          default: project
      - name: environment
        value:
          default: environment
```

2. Run the custom tagger, like: `yor tag --config-file custom_tagger.yaml --skip-tags 'yor_trace,git*' -d .`
3. Observe the created file, which looks correct/as expected (terraform example below):

```
  tags = {
    environment = "environment"
    project     = "project"
  }
```

4. Change the placeholders in the custom tagger to actual values, like:

```yaml
tag_groups:
  - name: tagger-test
    tags:
      - name: project
        value:
          default: foo
      - name: environment
        value:
          default: dev
```

5. Run the custom tagger a second time, like `yor tag --config-file custom_tagger.yaml --skip-tags 'yor_trace,git*' -d .`
6. Observe the CLI output, which appears correct (also see screenshot below).
7. Observe how the tag keys have been adjusted, just like the values:

```
  tags = {
    dev = "dev"
    foo = "foo"
  }
```

**Expected behavior**
Only the values for the tags should have been overwritten, not the keys:

```
  tags = {
    environment = "dev"
    project     = "foo"
  }
```

**Screenshots**
![image](https://user-images.githubusercontent.com/77016570/168148196-895d8a3b-0d11-42c2-8b8a-4373be63d9ab.png)
_The CLI output seems correct, only the value should have been updated, the tag key should have been unchanged._

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Yor Version v0.1.143
