### ISSUE TITLE
Error when using Yor in pre-commit on windows

### ISSUE THREAD

**Issue by mik3h0** [bridgecrewio/yor#279]
**Describe the bug**
Unable to run Yor via pre-commit in Windows

**To Reproduce**
1. Use Yor in pre-commit:
```
- repo: https://github.com/bridgecrewio/yor
  rev: 0.1.143
  hooks:
    - id: yor
      name: yor
      entry: yor tag --skip-tags git_last_modified_at -d
      args: ["."]
      language: golang
      types: [terraform]
      pass_filenames: false
```
3. Run cli command  `pre-commit run -a`
```
An unexpected error has occurred: FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\MichaelAnthonyHodgki\\.cache\\pre-commit\\repo_zacw2io\\golangenv-default\\pkg\\mod\\github.com\\!azure\\azure-sdk-for-go@v36.2.0+incompatible\\profiles\\preview\\preview\\enterpriseknowledgegraphservice\\enterpriseknowledgegraphservice\\enterpriseknowledgegraphserviceapi'
Check the log at C:\Users\MichaelAnthonyHodgki\.cache\pre-commit\pre-commit.log
```
**Expected behavior**
Yor tags resources

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Yor Version 0.1.143
