### ISSUE TITLE
Yor errors when parsing serverless.yml

### ISSUE THREAD

**Issue by anthonyangel** [bridgecrewio/yor#280]
**Describe the bug**
When parsing serverless.yml if `provider.deploymentBucket` is specified then Yor will error with `[WARNING] Failed to parser serverless yaml at serverless.yml due to: interface conversion: interface {} is map[string]interface {}, not serverless.DeploymentBucket`

**To Reproduce**
```
provider:
  name: aws
  deploymentBucket:
    blockPublicAccess: true
```

**Expected behavior**
Yor works

**Additional context**
It looks like this error comes from the `goserverless` package. https://github.com/thepauleh/goserverless/pull/10 is related
