### ISSUE TITLE
Yor is writing temp.[0-9]+.tf files instead of changing the source code

### ISSUE THREAD

**Issue by kayman-mk** [bridgecrewio/yor#281]
**Describe the bug**
Executing `yor` via pre-commit hook results in many temporary files, but none of my Terraform files is changed.

```
modules/global_export/temp.3293289490.tf
modules/global_keys/temp.1193803556.tf
modules/messaging/sns/temp.3597613450.tf
modules/shared/temp.813126445.tf
temp.82075535.tf
```

Looks like that `yor` created one temporary file per Terraform source file. No error message is shown.

Using `yor` via Docker works as expected.

**To Reproduce**
```
repos:
-   repo: https://github.com/bridgecrewio/yor
    rev: 0.1.143
    hooks:
      - id: yor
        name: yor
        entry: yor tag --directory
        args: ["."]
        language: golang
        types: [terraform]
        pass_filenames: false
``` 

Install the pre-commit hook and change a Terraform file. After `git commit` the temporary file appears.

**Expected behavior**
Have the Terraform source code changed (tags added).

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Yor: 0.1.143
