### ISSUE TITLE
Tagging based on workspace prefix / suffix?

### ISSUE THREAD

**Issue by andyshinn** [bridgecrewio/yor#335]
**Is your feature request related to a problem? Please describe.**
I would like to tag based on the workspace prefix. For example:

In the case of workspace `comqa` I would like to tag with:

- `segment:com`
- `env:qa`

Or in the case of workspace `govprod` I would like to tag with:

- `segment:gov`
- `env:prod`

I couldn't find a way to do this.

**Describe the solution you'd like**
I suppose this could be a sort of matcher for `matches`. Maybe there is a workspace matcher that can apply tags based on workspace such as:

```
name: env
value:
    default: prod
filters:
    workspaces:
      - comprod
      - govprod
```

Maybe with some way to do simple globs or prefix / suffix matching:

```
name: segment
  matches:
    - com:
        workspaces:
          prefixes:
              - com
name: env
  matches:
    - prod:
        workspaces:
          suffixes:
              - prod
        
```

**Describe alternatives you've considered**
I haven't tried any solutions as I haven't found anything in documentation to suggest it is currently possible.

**Additional context**
Thanks for considering!
