### ISSUE TITLE
Custom tags not being applied with --config-file flag or --custom-tagging flag

### ISSUE THREAD

**Issue by hwsonnnn** [bridgecrewio/yor#363]
**Describe the bug**
Hello,

I'm having an issue with Yor where custom tags are not being applied when using the --config-file flag and --custom-tagging flag. However, Yor works as expected when using the default tags without these flags. Here's the process I've followed:

1. I've created a custom_tags.yml file in the root directory with the following contents:

```
custom_tags:
  - key: "custom_key"
    value: "custom_value"
    paths:
      - "modules/ec2/*"
  - key: "another_key"
    value: "another_value"
    paths:
      - "modules/iam/*"
```
I ran the following command:
bash
`yor tag --config-file custom_tags.yml -d modules`
`yor tag --custom-tagging custom_tags.yml -d modules`

Yor seems to scan the resources, but it doesn't update the files with the custom tags. 
On the other hand, when I run yor tag -d ., the default tags are applied correctly.

I've also tried adding the default tags: section to the custom_tags.yml file, but I'm still experiencing the same issue.

Please let me know if there's something I'm missing or if there's a workaround for this issue. Thank you for your assistance!
<img width="674" alt="스크린샷 2023-05-08 오후 4 58 23" src="https://user-images.githubusercontent.com/130027459/236768883-306bc1ed-fd97-47d1-8619-614b56405324.png">

**Desktop (please complete the following information):**
 - OS: Mac M1
 - Yor version 0.1.174
