### ISSUE TITLE
is it possible to specify a list of directories in the pre-commit args: parameter?

### ISSUE THREAD

**Issue by stevesoutar** [bridgecrewio/yor#561]
i have a project with multiple modules, but i only want to enable yor tagging in a couple of directories for now, rather than letting yor tag dozens of modules at one pass

I tried variations on this format, but yor would only execute on the first path in the list 

My assumption is that the args: parameter currently does not attempt to cycle through this as a list, and only passes the first argument through for the -d path (as the behaviour suggests)

is it possible to supply a list of directories? Or not? 

these are some of the variations i tried (without success)

```yaml
    - repo: https://github.com/bridgecrewio/yor
      rev: 0.1.195
      hooks:
        - id: yor
          name: yor
          entry: yor tag -d
          args: ["directroy1/","directory2/"]
          language: golang
          types: [terraform]
          pass_filenames: false
```
or this

```yaml
    - repo: https://github.com/bridgecrewio/yor
      rev: 0.1.195
      hooks:
        - id: yor
          name: yor
          entry: yor tag -d
          args: [
                 "directroy2/",
                 "directory1/"
                ]
          language: golang
          types: [terraform]
          pass_filenames: false
```
