### ISSUE TITLE
Error retrieving git info "failed to get previous commit: object not found"

### ISSUE THREAD

**Issue by matty** [bridgecrewio/yor#615]
**Describe the bug**
I am running Yor inside an Azure DevOps YAML Pipeline and it appears to fail retrieving the git info, its possible that I am missing something when using the "checkout" stage of the pipeline but some guidance would be appreciated.

**To Reproduce**

I am running Yor install as a task:
```
steps:
  - task: Bash@3
    displayName: "Install Yor"
    inputs:
      targetType: 'inline'
      script: |
        export YOR_VERSION="${{ parameters.yorVersion }}"
        wget -q -O - https://github.com/bridgecrewio/yor/releases/download/${YOR_VERSION}/yor_${YOR_VERSION}_linux_amd64.tar.gz | tar -xvz -C /usr/local/bin/
```

And to apply I have

```
- task: Bash@3
    displayName: "Apply Yor"
    inputs:
      targetType: 'inline'
      script: |
        export YOR_SIMPLE_TAGS='{"terraform": "true"}'
        yor tag --directory "${{ parameters.terraformDirectory }}"
```
